FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y

WORKDIR /app
COPY environment.yml ./
RUN conda env create -f environment.yml && conda clean -afy

# Activate the conda environment for all subsequent commands
SHELL ["conda", "run", "-n", "applied-ai", "/bin/bash", "-c"]

COPY . .
CMD ["conda", "run", "--no-capture-output", "-n", "applied-ai", "python", "main.py"]