"""OpenAI chat client with conversation memory and guarded SQL execution.

Satisfies specs/chat.md AC-2, AC-3, AC-4, AC-5, AC-6, AC-7, AC-8.
Golden Rule 6: AI layer is read-only and user-scoped.
"""

import logging
import os
import re

from openai import OpenAI

from src.ai.prompts import fun_build_system_prompt
from src.ai.sql_guard import fun_validate_sql
from src.db.connection import fun_get_connection

logger = logging.getLogger(__name__)

MODEL = "gpt-4o-mini"
_RE_SQL_TAG = re.compile(r"<SQL>(.*?)</SQL>", re.DOTALL | re.IGNORECASE)

# PII column names scrubbed from query results before forwarding to OpenAI.
# Even if the LLM generates a SELECT that includes these columns, their values
# never leave the application boundary (Golden Rule 5 / CRITICAL-2 fix).
_PII_FIELDS = frozenset({"account_number", "phone", "email", "password_hash"})


class ChatSession:
    """Stateful chat session with conversation memory and SQL guard.

    Maintains a per-session message history so follow-up questions receive
    full context. When the LLM produces a <SQL>…</SQL> response, the query
    is validated by fun_validate_sql before execution. Only single user-scoped
    SELECTs are ever run against the database.

    Satisfies specs/chat.md AC-2, AC-3, AC-4, AC-5, AC-6, AC-7, AC-8.
    """

    def __init__(self, account_id: int, username: str) -> None:
        """Initialise a chat session for the given account.

        Raises EnvironmentError if OPENAI_API_KEY is not set.

        Args:
            account_id: Primary key of the user's bank account — used to scope
                        every SQL query generated by the assistant.
            username:   Display name injected into the system prompt.
        """
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "OPENAI_API_KEY environment variable is not set. "
                "Add it to your .env file."
            )
        self.account_id = account_id
        self._username = username
        self._history: list[dict] = []
        self._client = OpenAI(api_key=api_key)

    @property
    def history(self) -> list[dict]:
        """Return a shallow copy of the conversation history.

        Each entry is {"role": "user"|"assistant", "content": str}.
        This @property is intentionally named without the fun_ prefix
        because it is a data accessor, not a function per CODING_STANDARDS.

        Returns:
            list[dict]: Current conversation turns, oldest first.
        """
        return list(self._history)

    def fun_chat(self, user_message: str) -> str:
        """Send a user message and return the assistant's reply.

        Maintains conversation history across calls (AC-2). If the model
        responds with a <SQL>…</SQL> block, the query is validated (AC-5/AC-6),
        executed if valid (AC-3), and the model is asked to summarize the result.
        Prompt-injection attempts that produce non-SELECT queries are blocked by
        fun_validate_sql before the query ever reaches the database (AC-7).

        Args:
            user_message: The user's chat input.

        Returns:
            str: The assistant's final natural-language reply.
        """
        system_prompt = fun_build_system_prompt(self.account_id, self._username)

        messages = [{"role": "system", "content": system_prompt}]
        messages.extend(self._history)
        messages.append({"role": "user", "content": user_message})

        response = self._client.chat.completions.create(
            model=MODEL,
            messages=messages,
        )
        content = response.choices[0].message.content

        sql_match = _RE_SQL_TAG.search(content)
        if sql_match:
            sql = sql_match.group(1).strip()
            valid, reason = fun_validate_sql(sql, self.account_id)

            if valid:
                query_result = self._fun_run_query(sql)
            else:
                logger.warning("SQL rejected by guard: %s", reason)
                # The rejected SQL is intentionally NOT included in query_result
                # or any log statement to prevent logging injection payloads.
                query_result = f"Query rejected: {reason}"

            summary_messages = messages + [
                {"role": "assistant", "content": content},
                {
                    "role": "user",
                    "content": (
                        f"Query result: {query_result}\n"
                        "Please summarize this for the user in plain language."
                    ),
                },
            ]
            summary_response = self._client.chat.completions.create(
                model=MODEL,
                messages=summary_messages,
            )
            final_content = summary_response.choices[0].message.content
        else:
            final_content = content

        self._history.append({"role": "user", "content": user_message})
        self._history.append({"role": "assistant", "content": final_content})
        return final_content

    def fun_clear(self) -> None:
        """Reset conversation history, starting a fresh session.

        Satisfies AC-8 (FR-AI-07).

        Returns:
            None
        """
        self._history = []

    def _fun_run_query(self, sql: str) -> str:
        """Execute a guard-approved SELECT and return scrubbed results as a string.

        Private — only called from fun_chat after fun_validate_sql returns True.
        PII columns (account_number, phone, email, password_hash) are scrubbed
        from the result rows before they are forwarded to OpenAI (Golden Rule 5).

        Args:
            sql: A validated single user-scoped SELECT statement.

        Returns:
            str: Query results (PII-scrubbed) as a string, or an error message.
        """
        try:
            conn = fun_get_connection()
            conn.autocommit = False  # explicit read-only intent
            cursor = conn.cursor(dictionary=True)
            cursor.execute(sql)
            rows = cursor.fetchall()
            cursor.close()
            conn.close()
            if not rows:
                return "No matching data found."
            # Scrub PII fields before the results leave the application boundary.
            clean_rows = [
                {k: v for k, v in row.items() if k not in _PII_FIELDS}
                for row in rows
            ]
            return str(clean_rows)
        except Exception as exc:
            logger.error("Query execution error: %s", type(exc).__name__)
            return "Query execution failed."
