"""SQL guard: validate that a query is a single user-scoped SELECT.

Satisfies specs/chat.md AC-5, AC-6, AC-7.
Golden Rule 6: the AI layer is read-only and user-scoped.
"""

import re

# Line comments (-- ...) and block comments (/* ... */).
_RE_LINE_COMMENT = re.compile(r"--[^\n]*")
_RE_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)

# String literals — strip them before keyword and scope scanning to avoid false
# positives from user-supplied note/category text that contains keywords.
_RE_STRING_LITERAL = re.compile(r"'(?:[^'\\]|\\.)*'", re.DOTALL)

# Forbidden DML / DDL / administrative keywords.
# NOTE: this scan MUST run after the multi-statement check (line 63) because
#       the multi-statement check is cheaper and catches more payloads first.
#       Changing the order would not create a security hole, but it would allow
#       payloads like "SELECT 1; DROP TABLE" to bypass the forbidden-keyword
#       check on the first half.  Keep the order: split → SELECT-check → keyword-scan.
_RE_FORBIDDEN = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|GRANT|REVOKE|"
    r"EXECUTE|EXEC|CALL|REPLACE|MERGE)\b",
    re.IGNORECASE,
)

# File-exfiltration patterns (multi-word, handled separately).
_RE_INTO_OUTFILE = re.compile(r"\bINTO\s+OUTFILE\b", re.IGNORECASE)
_RE_LOAD_DATA = re.compile(r"\bLOAD\s+DATA\b", re.IGNORECASE)


def fun_validate_sql(sql: str, account_id: int) -> tuple[bool, str]:
    """Validate that a SQL string is a single user-scoped SELECT statement.

    Validation steps (all must pass for True):
      1. Non-empty after stripping SQL comments.
      2. Single statement — no additional statements after a semicolon.
      3. First keyword is SELECT (case-insensitive).
      4. No forbidden DML/DDL keywords or exfiltration patterns in the
         non-string-literal portion of the query.
      5. The pattern ``account_id = <value>`` (with optional spaces) appears in
         the string-literal-stripped query, confirming the query is scoped to
         the current user's account.  Checking against the stripped query
         prevents the account_id from being hidden inside a string literal.

    The function never executes the query. Satisfies AC-5, AC-6, AC-7.

    Args:
        sql:        The SQL string generated by the LLM to validate.
        account_id: The current user's account_id that must appear in the query.

    Returns:
        tuple[bool, str]: (True, "") if valid; (False, reason) if not.
    """
    if not sql or not sql.strip():
        return False, "Empty query."

    # Step 1 — strip comments; account_id must appear in live SQL, not a comment.
    cleaned = _RE_LINE_COMMENT.sub(" ", sql)
    cleaned = _RE_BLOCK_COMMENT.sub(" ", cleaned)
    cleaned = cleaned.strip()

    if not cleaned:
        return False, "Query is empty after removing comments."

    # Step 2 — multiple statements: split on semicolons and count non-empty parts.
    parts = [p.strip() for p in cleaned.split(";") if p.strip()]
    if len(parts) > 1:
        return False, "Multiple statements are not allowed."

    # Step 3 — first keyword must be SELECT.
    tokens = cleaned.split()
    if not tokens or tokens[0].upper() != "SELECT":
        return False, "Only SELECT statements are allowed."

    # Step 4 — forbidden keywords and exfiltration: check after stripping string
    # literals so text in note/category values cannot spoof a keyword.
    no_strings = _RE_STRING_LITERAL.sub("''", cleaned)

    forbidden_match = _RE_FORBIDDEN.search(no_strings)
    if forbidden_match:
        return False, f"Forbidden operation: {forbidden_match.group()}."

    if _RE_INTO_OUTFILE.search(no_strings):
        return False, "INTO OUTFILE is not allowed."

    if _RE_LOAD_DATA.search(no_strings):
        return False, "LOAD DATA is not allowed."

    # Step 5 — user scope: require the pattern ``account_id = <value>`` in the
    # string-literal-stripped query.  This is tighter than a bare integer search
    # (prevents LIMIT 42 from satisfying the scope check) and applies to the
    # stripped version (prevents hiding the value inside a string literal).
    scope_pattern = re.compile(
        r"account_id\s*=\s*" + re.escape(str(account_id)),
        re.IGNORECASE,
    )
    if not scope_pattern.search(no_strings):
        return False, "Query must be scoped to your account (account_id = <id> not found)."

    return True, ""
